# permissions for end users to edit gitops.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: gitops-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: turbo-gitops
    app.kubernetes.io/part-of: turbo-gitops
    app.kubernetes.io/managed-by: kustomize
  name: gitops-editor-role
rules:
- apiGroups:
  - gitops.turbonomic.io
  resources:
  - gitops
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gitops.turbonomic.io
  resources:
  - gitops/status
  verbs:
  - get
