---
apiVersion: gitops.turbonomic.io/v1alpha1
kind: GitOps
metadata:
  name: gitops-sample-1
spec:
  config:
  - commitMode: direct
    selector: "*"
---
apiVersion: gitops.turbonomic.io/v1alpha1
kind: GitOps
metadata:
  name: gitops-sample-2
spec:
  config:
  - commitMode: direct
    whitelist:
    - app1
    - app2
---
apiVersion: gitops.turbonomic.io/v1alpha1
kind: GitOps
metadata:
  name: gitops-sample-3
spec:
  config:
  - commitMode: direct
    selector: "^turbo.*$"
    whitelist:
    - app1
    - app2
---
apiVersion: gitops.turbonomic.io/v1alpha1
kind: GitOps
metadata:
  name: gitops-sample-4
spec:
  config:
  - commitMode: direct
    selector: "^turbo.*$"
    credentials:
      email: turbo@turbonomic.com
      username: turbo
      secretName: gitops-token
      secretNamespace: turbonomic
